<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Biomundo.Data\Biomundo.Data.csproj" />
    <ProjectReference Include="..\Biomundo.Sync\Biomundo.Sync.csproj" />
    <ProjectReference Include="..\Biomundo.AI\Biomundo.AI.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
